### PR TITLE
Implement bonjour and target option for "frank console".

### PR DESCRIPTION
**Pull request by suzumura-ss**
Hi there.

I was implemented `--bonjour` and `--target=<URL>` options for `frank console`, for testing of the physical device.
- `--bonjour` option, FrankHelper connect to the physical device via bonjour.
- `--target=<URL>` option, FrankHelper connect to the `URL`.

### CODE REVIEW

**Comment by ondrejhanslik** [comment]
Nice addition but I would rename `--target` to something better. Maybe `url` or `ip`?

**Comment by kkendall33** [comment]
Checkout the method "test_on_physical_device_with_ip" in frank_helper.rb.  Pete merged it a few days ago, does it do something similar to this?

**Comment by moredip** [comment]
My preference would be --server rather than --target.

Cheers,

## Pete

Typed on a little bitty keyboard

**Comment by suzumura-ss** [comment]
I agree. I also think a good prefer --server than --target.

**Pull request merged**
