### PR TITLE
Upstream master

### PR DESCRIPTION
**Pull request by olarivain**
Hey Pete,

Here's a patch that'll enable handy scrolling in scroll, table and map views, along with cucumber steps for convenience.

The naming of the params on the objc side is a little bit odd, due to camel casing (x is upper case, y isn't), but since  steps are provided, users shouldn't have to worry about that detail.

I've tried to keep consistent with the phrasing of the other existing steps, but I'm not a native english speaker, so let me know if there's an obvious english mistake in the step names :)

### CODE REVIEW

**Comment by moredip** [comment]
Thanks Kra, this is very helpful. Hope you don't mind if I rename the frank_ category extension methods to FEX_, for consistency with other frank extension methods.

**Comment by olarivain** [comment]
Aaah, Frank EXtension, i wondered what that prefix was and thought it was from some other project.
Perfectly fine with me!

/kra

**Comment by moredip** [comment]
I made a few other changes too. I replaced the canned cucumber steps with some ruby helper methods - I'm trying to encourage users to write their cuke steps in business language rather than low-level UI language. 

I also pulled the mapkit helper out - it seemed to be causing issues with projects that weren't using the mapkit framework. Not sure what the best solution is to that. I think it'd be better to implement that helper as an extension method to UIView which uses dynamic message sending to call the mapkit method on itself.

**Comment by olarivain** [comment]
Yeah, I can't disagree with that. I'm coming down to same conclusions after working on our massively complex registration process.
At first, i tought we would get away with features full of When I touch foo then I should see bar.
Turns out we have to constantly call out to ruby code to fetch our reference data from the server and we either have to create custom steps to fetch data (looks weird in the feature), or shove the steps in the ruby code with the nasty step %q|I should see whatever|.
We would be better off with a few high level steps per scenario, and the current gem doesn't really encourage this, making apps with highly dynamic data to be somewhat cumbersome to automate.
Now, my apps are fairly big, highly data driven, with the data being highly user specific, so it's probably the exception more than the rule.

On a different subject, I've been hitting a few walls recently with text fields, and more generally the usual UIKit behaviour of "setting the view programmatically doesn't call the delegate".
We typically have delegates enforcing a text view doesn't have more than 1000 characters, forbidding whatever character, and there's just no simple way to test this right now.

I don't know if UIAutomation would address this, but if it doesn't, it sounds like frank should come with automation categories that would emulate the regular behavior.
Typically setting text would set the text char by char, calling the relevant deleagte methods one by one, effectively simulating user input.
I'd really love to take a look into this, if I can set aside some time to play with that, could be very beneficial to Frank and clean up one of the last remaining difficulties with the project.

/kra

**Pull request merged**
