### PR TITLE
Fix for scroll view's scrollToTop/Bottom

### PR DESCRIPTION
**Pull request by olarivain**
Hey,

Here's a fix for QK's issue on the mailing list, about UIScrollView -scrollToBottom not working.
You might want to double check the commit that updated the KIF submodule, I'm not quite sure why I did that.

/kra

### CODE REVIEW

**Comment by moredip** [comment]
Hey Kra, I won't pull this in as is because we don't want that KIF submodule update. It rolls Frank back to using the stock KIF release, which has a bug touching rectangular views in landscape orientations.

I'll go ahead and just cherry-pick your c8de7c3 commit.

**Comment by olarivain** [comment]
Yeah, I don't know what I was on when I committed that. :)

On a different topic, I'm looking at things I'd like to contribute, among these:
- adding utility categories on views, among the same line of these UIScrollView categories (scroll to a cell marked on table, scroll one page in either direction and things like that)
- try to remove direct dependency on UISpec (why is there still a direct dependency on UISpec btw? I thought it was supposed to be deprecated?).
- some more work towards gestures support. The current support is flaky at best, UIAutomation framework would solve it reliably and with little code on the simulator but just isn't available on devices.
  I'm not sure what to do with this, looks like custom gestures are too complex to be properly reverse engineered and are never going to be fully functional on devices, so maybe providing it as an optional .a, enabled only for simulator would be an option? At least that'll enable them reliably.

Any thoughts on things you'd like to see or on the value of these points for the project?

/kra

**Comment by moredip** [comment]
Breaking up the project a bit (UISpec in a seperate static lib) would be great, and solid gesture support would also be great. Might be worth taking a look at Calabash's implementation (they're open to collaboration/sharing between Frank and Calabash).

Adding utility categories would be good, but I think it can be done piecemeal as needed. Doesn't seem worth trying to second guess what would be useful.

**Comment by olarivain** [comment]
Sounds good then.
I'll start working on a break down in modules, from there it should make it easier to work on things like gesture support.

I'll create a dedicated branch on my fork and will let you know when it's in a decent state.

/kra

**Pull request closed without merging**
