### PR TITLE
Add FEX_isUserVisible, iOS unit test target, Gemfile to Controls

### PR DESCRIPTION
**Pull request by rhgills**
Adds a `FEX_isUserVisible` category method on UIView, which optionally strengthens the predicate `FEX_isVisible` to only be user visible when the view in question is not completely obscured on screen by another view. `FEX_isUserVisible` is unit tested and has a example view in the Controls app. An iOS unit test target has been added to the project, which I hope will encourage greater test coverage going forwards. 

I also added a Gemfile to the Controls example, which points to the copy of the gem in the local repository. As long as you remember to `bundle`, you'll always be running Controls with the cloned version of Frank.

`FEX_isUserVisible` could be improved to check that the view is actually positioned on screen and not completely off of it.

Let me know what you think!

### CODE REVIEW

**Comment by ondrejhanslik** [comment]
Hi, I don't think this will ever work reliably. Note there are too many possibilities when the test fails. To name a few:
1. view overlapped by a visible view, with alpha = 1.0 but filled up by a clear color.
2. view overlapped by a non-transparent layer
3. view overlapped by views in a different window (e.g. keyboard window)
4. view that is drawn outside its bounds can be tested only inside its bounds because the system has no information about what is drawn outside its bounds
5. `UIImageView` with a transparent image
6. View with a modified value of its `layer.zPosition`.

**Comment by rhgills** [comment]
I see your point. The original motivation behind this method was to work around frank seeing a menu (in a child view controller) that was completely below and obscured by the other child view controller of the parent, the actual content view. Think the common sidebar/hamburger idiom, where the menu is underneath the content view until opened. I'm starting to think that a better solution is to change the client code to, when the menu is completely obscured, remove it from the view hierarchy or at least set isHidden to YES. As much as I'm hesitant to change client code for the purposes of tests, it seems cleaner this way before even considering Frank.

**Comment by ondrejhanslik** [comment]
Using `hidden` is usually my fix because it also improves drawing performance. You can also try to use `FEX_canTouch` which will tell you if the view can be touched. 

However, not all test cases can be automatized. Some of them will always need a human tester.

**Comment by rhgills** [comment]
Didn't know about `FEX_canTouch`; that should come in handy. 

Completely agree with you there.

**Pull request closed without merging**
