### PR TITLE
Minor fixes for Shelley

### PR DESCRIPTION
**Pull request by olarivain**
Hey Pete,

I'm back :)

I just fixed a few minor things here, mostly to give shelley a better support:
- added short hand notation support for alert view/action sheet to shelley (e.g. When I touch the "Logout" alert view button step). These were dead simple, just add the missing name/classes to SYParser
- Something that looked like a typo in the "I should see an alert view titled" step. Basically, it was matching the alert view by message rather than title. Just swapped title/message and it works fine (granted that you want to check against the title, not the message, of course)
- Also, I've added a sleep 1 to When I navigate back step, using that with shelley causes the navigation stack to freak out when you tap it more than once. I guess the second tap happens before the pop animation has finished, so you end up in a weird state, at level - 2, but with the title of -1.
  Note that this sounds more like a UIKit issues (it usually doesn't appreciate it when you monkey with the stack in the middle of a navigation animation), so it most likely also affect UIQuery.

I gotta say, Frank really is awesome, just played a couple of hours automating an app, it's dead simple and I actually got a decent set of coverage in... Great job man!

Enjoy WWDC and say hi to Tim Cook for me :)

### CODE REVIEW

**Comment by moredip** [comment]
Kra, thanks for all this - great stuff. The only think I don't agree with is the sleep in aaf9bc1. Can you revert that one commit, do a merge against my current master and then add a comment here so I know I can pull? Thanks dude.

**Comment by olarivain** [comment]
Sure will do.
Expect the updated pull request sometime today.

**Comment by olarivain** [comment]
raaah.
I hate git submodule.
If I understand properly the merge problem I'm facing here:
- I have to clone your shelley submodule, reapply my shelley patch there and submit a pull request for that change
- then update the submodule revision in my frank clone
- open a new pull request for the other changes in frank.

this pretty much makes this pull request worthless, so I'm closing it.

**Comment by olarivain** [comment]
Here are the pull requests:
Shelley: https://github.com/TestingWithFrank/Shelley/pull/1
Frank: https://github.com/moredip/Frank/pull/111

**Pull request closed without merging**
