### PR TITLE
Give a better error message if the accessibility check fails because there is no UI window

### PR DESCRIPTION
**Pull request by jacklynrose**
This happened:
http://fluffyjack.roon.io/always-check-the-source-code

### CODE REVIEW

**Comment by moredip** [comment]
Great idea. Thanks for helping future folks getting started!

**Comment by moredip** [comment]
@FluffyJack actually I just realized this doesn't pass CI. Specifically, it looks like the OS X version doesn't compile now.
https://travis-ci.org/moredip/Frank/builds/14402070

To reproduce this locally you probably just need to compile the OS X target Frank target in XCode. Alternatively, just run `rake` from the root of the Frank project.

**Comment by moredip** [comment]
Oh and for bonus points if you could convert the `[NSDictionary dictionaryWithObjects:]` and `[NSArray arrayWithObjects:]` usage to `@{}` and `@[]` while you're in that file I'd be very grateful.

**Comment by jacklynrose** [comment]
Sorry, did it real quick and just submitted it. I'll fix it up soon :)

**Pull request closed without merging**
