### PR TITLE
Pass all windows to selector engines

### PR DESCRIPTION
**Pull request by lukeredpath**
This extends the selector engine protocol to support the passing of an array of windows in which the selector engine should attempt to match views.

This makes it possible for selector engines to implement multi-window support without needing to know anything about the FEX_windows category method.

I'm working on a pull request for Igor to support this; Shelley would need the same, but it's backwards compatible.

Perhaps consider deprecating the old method?

### CODE REVIEW

**Comment by moredip** [comment]
I like the approach @lukeredpath. I'd be happy to pull it in, but from the Travis fail it looks like you [inadvertently broke the OS X build of Frank](https://travis-ci.org/moredip/Frank/builds/12530117).

You'll need to add some preprocessor #ifdefs to avoid referencing UIKit stuff in the OS X build. I'm happy to help with this - let me know if so.

**Comment by lukeredpath** [comment]
@moredip thanks, I'll get onto this today.

@dhemery asked about the possibility of this potentially breaking tests if queries start matching elements in multiple windows. I consider the possibility slim, although I did run into some issues in my own tests with some custom modal code of mine that uses a new window.

In my case, I was able to work around this with Igor by simply extending my query to look for views in the key window (which was easy to do in Igor, see my comments on the Igor pull request). This would have to be tested with Shelley (obviously the whole new protocol method needs adding to Shelley anyway).

**Comment by lukeredpath** [comment]
@moredip hopefully that change will do the trick. This makes the protocol extension iOS-only for now as I wasn't sure how to make an equivalent call for OSX.

**Comment by lukeredpath** [comment]
@moredip any updates on this?

**Comment by moredip** [comment]
Sorry, been slammed at work. I will get to this ASAP.

**Comment by seanoshea** [comment]
Apologies if this isn't the correct place to ask this question, but with this code change in Frank, it sounds like we'd need something similar in Shelley to ensure that UIAlertViews are query-able in iOS7. Or, will this code change alone in Frank ensure that UIAlertViews are query-able in iOS7?

Posted on the Frank discussion groups if this is not the correct forum for this discussion: https://groups.google.com/forum/#!topic/frank-discuss/As_htm9b5L4

**Comment by lukeredpath** [comment]
@seanoshea yes, Shelley would need to be modified to support the extended selector engine protocol to perform a search across all of the windows it is passed. I've already made this change to the Igor query engine in my fork (which is what I use): https://github.com/lukeredpath/igor/commits/add-support-for-multiple-windows

**Comment by jberkel** [comment]
@seanoshea check my fork of frank: https://github.com/jberkel/Frank/tree/multiple-windows
still WIP but will submit a PR once it is done

**Comment by seanoshea** [comment]
@lukeredpath Sweet - thanks for the pointer. I've never really looked into selector engines for iOS, but this conversation has definitely piqued my interest.

**Comment by seanoshea** [comment]
@jberkel Awesome. Thanks for looking into this - I'm sure there are PLENTY of Frank/Shelley users that are worried about iOS7 support - hopefully your PR helps solve the root of the issue. Happy to help out on testing it out against our suite of automation tests if you want to ping me when you're close to being finished.

**Comment by jberkel** [comment]
@seanoshea do you use the core steps in included with frank to test alert views ? `I should see an alert view with the message ...` etc?

with the patch to shelley it is possible to access the UI hierarchy but the implementation has completely changed so might require some more changes to the core steps.

**Comment by seanoshea** [comment]
@jberkel Yep - that's the step that we're using to either read the title or the message from the UIAlertView. We also have steps for dismissing a UIAlertView.

**Comment by seanoshea** [comment]
Specifically, we make heavy use of the following steps:

```
Then /^I should see an alert view titled "([^\"]*)"$/ do |expected_mark|
  wait_for_nothing_to_be_animating( WAIT_TIMEOUT )
  values = frankly_map( 'alertView', 'title')
  values.should include(expected_mark)
end

Then /^I should see an alert view with the message "([^\"]*)"$/ do |expected_mark|
  if is_ipad
    sleep( STEP_PAUSE )
  else
    wait_for_nothing_to_be_animating( WAIT_TIMEOUT )
  end

  values = frankly_map( 'alertView', 'message')
  values.should include(expected_mark)
end

When /^I touch the "([^\"]*)" alert view button$/ do |mark|
  quote = get_selector_quote(mark)
  touch_with_sleep( "alertView threePartButton marked:#{quote}#{mark}#{quote}" )
end

When /^I touch the (\d*)(?:st|nd|rd|th)? alert view button$/ do |ordinal|
  ordinal = ordinal.to_i
  touch_with_sleep( "alertView threePartButton tag:#{ordinal}" )
end

When  /^I dismiss the alert$/ do
  wait_for_nothing_to_be_animating( WAIT_TIMEOUT )

  remove_alert_view
end
```

**Comment by ondrejhanslik** [comment]
There are several problems here:
1. Ruby steps don't know the iOS version now, it should be added to the dictionary returned by DeviceCommand (https://github.com/moredip/Frank/blob/master/src/DeviceCommand.m)
2. Then it will be a simple task of an if-else branch to replace the name of the old view by the new view on iOS 7 (e.g. table cell instead of button)
3. wait_for_nothing_to_be_animating needs a fix in Shelley. The current implementation looks for all animations but there is always a paralax animation on alerts, so the wait never ends. See https://github.com/ondrejhanslik/Shelley/commit/c6c49d42681d7824786b43c69a2dad23ec61f42c

**Comment by seanoshea** [comment]
@ondrejhanslik what do you think about opening a pull request for your third point? Or, would you only have this logic implemented if you are running in iOS7 or later?

**Comment by ondrejhanslik** [comment]
I just did. I have a pretty long queue for Shelley extensions so I forgot a bit about this one.

**Comment by seanoshea** [comment]
@ondrejhanslik would something like https://github.com/seanoshea/Frank/commit/d2b65b0363cf15fde47c98760eb27bd29cd72041 work for point number 1 above?

**Comment by lukeredpath** [comment]
Before I step out of this discussion, I thought I'd leave you with my notes on how we got alert view tests working, bearing in mind that we a) use Igor, not Shelley and b) don't use Cucumber (I'm using a custom approach built around MiniTest).
- I ran into the issue with `isAnimating` needing to account for motion effects too; my fix wasn't as nice @ondrejhanslik's (I was specifically checking for a parallax effect) so I'll probably update my implementation (I've copied the category into my project as we don't link against Shelley).
- The view hierarchy for UIAlertView on iOS7 is crazy - in fact I'm not sure UIAlertView itself actually ends up in the view hierarchy. Instead, I'm querying for `_UIModalItemRepresentationView` as the overall alert view container view, looking for UILabel's within that container to match against the title, and bizarrely, the buttons are implemented as a `UITableView` so you're looking for a `_UIModalItemTableViewCell` containing a label matching the button text you are looking for.

In Igor, the queries are, respectively:

```
$_UIModalItemRepresentationView UILabel[accessibilityLabel=TITLE] # alert with title TITLE
_UIModalItemRepresentationView $_UIModalItemTableViewCell UILabel[accessibilityLabel=LABEL] # alert view button with label LABEL
```

**Comment by ondrejhanslik** [comment]
@seanoshea I would use `os_version` instead of `version`. Also, could you please add a ruby method `frankly_os_version` or something similar to `frank_helper` (https://github.com/moredip/Frank/blob/master/gem/lib/frank-cucumber/frank_helper.rb#L423)? I am sorry that I am not doing it myself - I already have the necessary things in my head but I don't currently have the time to implement and test them.

**Comment by ondrejhanslik** [comment]
@lukeredpath UIAlertView is definitely not a part of the hierarchy. Using tables for buttons is strange but it's not new (the same applies for action sheets, for example). The interesting part is that the cell views have accessibility flags marking them as buttons. I hope I wlll finish my commit including accessibility into Shelley soon. Then we will be able to drop checks for os version.

**Comment by seanoshea** [comment]
@ondrejhanslik Will give that a try. Thanks for the pointers.

**Comment by seanoshea** [comment]
@ondrejhanslik done in https://github.com/seanoshea/Frank/commit/17f584ce808811f4d1c7369fe84bd7e4c398d517 and https://github.com/seanoshea/Frank/commit/799868dd4da53b754a5533227fb1698bac4d8828. So, this should allow frank to get access to the iOS/Mac version. Should I open a pull request for this if you require it for your UIAlertView work?

**Comment by ondrejhanslik** [comment]
Please, open pull request for both, i will merge them.

**Comment by seanoshea** [comment]
Done at https://github.com/moredip/Frank/pull/254

**Comment by seanoshea** [comment]
@jberkel Is your Frank branch necessary if https://github.com/moredip/Frank/commit/d2b73e81ac3328875dbab2338788553a40b360a9 has been merged into the master branch for Frank? Sounds like Shelley just needs to be altered to receive an array of windows instead of just the application's window now?

**Comment by jberkel** [comment]
no, the only change is that it points to the forked version of shelley.

**Comment by seanoshea** [comment]
OK - awesome. So, it looks like the only thing necessary now for ensuring that UIAlertViews are visible to Frank in iOS 7 is some changes to the frank steps? Thanks for opening the Shelley PR.

**Comment by jberkel** [comment]
yes, since the view hierarchy has completely changed - `UIAlertView` is not even part of it

**Comment by seanoshea** [comment]
OK - I'll try to open a new issue on the Frank repo to track the `UIAlertView` issue between iOS 6 and iOS 7. Or, https://github.com/moredip/Frank/issues/234 looks like a good candidate to reuse as a bug for iOS 7 and `UIAlertView`

**Comment by seanoshea** [comment]
@jberkel @ondrejhanslik Would something like this work: https://gist.github.com/seanoshea/7613671

**Comment by seanoshea** [comment]
@moredip @jberkel @ondrejhanslik. Updated the gist (https://gist.github.com/seanoshea/7613671) and have tested it in my local repo & it seems to work fine.

I basically just checked out the https://github.com/moredip/Frank repo, built it against the 'Frank' target which produced the following files:

```
libCocoaAsyncSocket.a
libCocoaHTTPServer.a
libCocoaLumberjack.a
libFrank.a
libShelley.a
```

I popped these into my Frankified application and ran the tests against an iOS 7 simulator and it worked fine with the updated selector that I outlined in the gist.

I can't seem to execute a `frank console` command though to connect to the application after putting the new .a files into my Frankified app. Unsure if I built them incorrectly, or if there's any way to debug these types of issues. Would appreciate some help if there's something I've missed out on when building the .a files.

**Comment by ondrejhanslik** [comment]
What is the result of "frank console"?

**Comment by seanoshea** [comment]
My bad. Seems to be working fine now after a rebuild.

**Pull request merged**
