### PR TITLE
Fix applescript execution issue (System Events reports error) with OS X 10.9 Mavericks

### PR DESCRIPTION
**Pull request by jtomson**
Hello,

Running frank under OS X 10.9 I would receive the following error when invoking `press_home_on_simulator`:

```
71:158: execution error: System Events got an error: menu item "Home" of menu "Hardware" of menu bar of process "iPhone Simulator" doesn’t understand the “click” message. (-1708)
```

Specifying `menu bar 1` instead of `menu bar` seems to have resolved the issue.

Thanks,
James

### CODE REVIEW

**Comment by jtomson** [comment]
This may only be necessary when using the iOS Simulator w/ **Xcode 5**

**Comment by moredip** [comment]
Are you able to test this on a non-Mavericks machine to check it doesn't cause regressions? Alternatively, can you explain what the change actually does - AppleScript is an obscure magic to me :)

**Comment by jtomson** [comment]
I am no applescript expert, but apparently just referring to "menu bar" without qualifying the number is incorrect: "menu bar 1" should be specified for the app's main menu bar entries, and "menu bar 2" is used for "menu extras" owned by an application[0][1]

Also to note, the other applescript-invoking method in this particular file, `simulator_reset_data`, explicitly uses "menu bar 1".

So that being said I haven't tested on a pre-10.9 machine, but this change should be harmless...

[0]https://discussions.apple.com/message/12979686#12979686
[1]http://www.macosxautomation.com/applescript/uiscripting/index.html

**Comment by moredip** [comment]
Makes sense. Thanks for the clear explanation.

**Pull request merged**
