### PR TITLE
Add 'fill_in' text field helper

### PR DESCRIPTION
**Pull request by danielwellman**
Created a helper for setting text in text fields in the style of Capybara's "fill_in".

Usage example:

  fill_in 'Email address', :with => 'myfake@...'
  fill_in 'First name', :with => 'Dan'

Updated the built-in step "When /^I type "([^\"]_)" into the "([^\"]_)" text field$/" to use this helper.

### CODE REVIEW

**Comment by maciekish** [comment]
How do i use this?

When I type "maciekish" into the "Username" text field

Doesn't work, Frank says it's not implemented

**Comment by danielwellman** [comment]
@maciekish I can't tell from your example, but it looks like you're providing some example Gherkin that might appear in a Cucumber feature file - and would match a step definition. The code referenced in this pull request cannot be used as a step definition; rather, it can be used in a step definition that you create.  

So you might use it in a step definition like this:

```
When "I log in to the system" do
  fill_in 'login', :with => 'me@example.com'
  fill_in 'password' :with => 'abc123'
  # ...
end
```

It looks like the core step for typing has since been removed and possibly replaced with something else.

**Comment by maciekish** [comment]
This page lists the step i used as a "supplied step" http://www.testingwithfrank.com/supplied_steps.html

Are you saying it's been removed? I realize you may not be responsible for the page but i guess you may know something anyway.

**Comment by danielwellman** [comment]
I'm not sure; it looks like it may have been removed.  @moredip might have some insight?  It looks like the core steps do not contain typing instructions: https://github.com/moredip/Frank/blob/master/gem/lib/frank-cucumber/core_frank_steps.rb

If you have the option, I'd encourage you to try to write your scenarios in a way where the low-level details of what are being typed live inside of the step definitions, and the high level steps talk about the higher level business use case -- for example use "When I log in with valid credentials" instead of "When I type in x and y And When I press the Login Button".  I've found this leads to tests that are easier to change when the UI changes, and removing details from the acceptance tests can make them easier to understand their intent.  Here's an example: http://www.cyrusinnovation.com/improve-your-ios-frank-cucumber-acceptance-tests/

That said, sometimes you may need a quick step for an experiment; if that's the case, perhaps you can write your own step in your project using the `fill_in` method?

**Pull request merged**
