### PR TITLE
Image capture crashes on iOS7

### PR DESCRIPTION
**Pull request by lukeredpath**
I'm still investigating this, but I'm seeing issues where image capture at the end of each of my tests was causing the app to crash.

Unsure if this is a problem isolated to my app or not and so far I've only seen this on our CI build slave. Here's a backtrace:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   WebCore                             0x072671bc -[TileHostLayer renderInContext:] + 44
1   QuartzCore                          0x01a61646 -[CALayer _renderSublayersInContext:] + 413
2   QuartzCore                          0x01a5fb8c -[CALayer renderInContext:] + 1483
3   QuartzCore                          0x01a61646 -[CALayer _renderSublayersInContext:] + 413
4   QuartzCore                          0x01a5fb8c -[CALayer renderInContext:] + 1483
5   QuartzCore                          0x01a61646 -[CALayer _renderSublayersInContext:] + 413
6   QuartzCore                          0x01a5fb8c -[CALayer renderInContext:] + 1483
7   QuartzCore                          0x01a61646 -[CALayer _renderSublayersInContext:] + 413
8   QuartzCore                          0x01a5fb8c -[CALayer renderInContext:] + 1483
9   QuartzCore                          0x01a61646 -[CALayer _renderSublayersInContext:] + 413
10  QuartzCore                          0x01a5fb8c -[CALayer renderInContext:] + 1483
11  CAN                                 0x0016e12f +[UIImage(Frank) imageFromApplication:resultInPortrait:] + 1520 (UIImage+Frank.m:61)
12  CAN                                 0x0016eaf0 -[ImageCaptureRoute handleRequestForPath:withConnection:] + 445 (ImageCaptureRoute.m:150)
13  CAN                                 0x0016a536 __53-[RequestRouter handleRequestForPath:withConnection:]_block_invoke + 53 (RequestRouter.m:68)
14  libdispatch.dylib                   0x03382444 _dispatch_barrier_sync_f_slow_invoke + 71
15  libdispatch.dylib                   0x033934b0 _dispatch_client_callout + 14
16  libdispatch.dylib                   0x03381766 _dispatch_main_queue_callback_4CF + 340
17  CoreFoundation                      0x039afa5e __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
18  CoreFoundation                      0x038f072b __CFRunLoopRun + 1963
19  CoreFoundation                      0x038efb33 CFRunLoopRunSpecific + 467
20  CoreFoundation                      0x038ef94b CFRunLoopRunInMode + 123
21  GraphicsServices                    0x03e9c9d7 GSEventRunModal + 192
22  GraphicsServices                    0x03e9c7fe GSEventRun + 104
23  UIKit                               0x01c9a94b UIApplicationMain + 1225
```

I'll update this issue as I get more information.

### CODE REVIEW

**Comment by lukeredpath** [comment]
Right, so I was able to reproduce this locally. Instead of spending ages trying to debug the issue, it seemed far better to use the new APIs in iOS7 to render the view, if they are available.

So instead of:

``` objc
[window.layer.presentationLayer renderInContext:UIGraphicsGetCurrentContext()];
```

We can use:

``` objc
[window drawViewHierarchyInRect:window.bounds afterScreenUpdates:YES];
```

This seems to work perfectly without crashing. A pull request will be forthcoming.

**Comment by ondrejhanslik** [comment]
Could you try it with`[window.layer renderInContext]`? Without `presentationLayer`? The beauty of using presentationLayer is that you can capture a screenshot during animations.

Is it possible to reproduce the issue on iOS 6?

**Comment by lukeredpath** [comment]
I never saw the issue once on iOS 6 although that was compiled with the old SDK, and that's after months of running these tests on our CI slave. 

It makes sense to me to use the documented APIs if available though. 

I've noticed it doesn't crash on all of my tests, so it might be a particular layout causing it.

**Comment by lukeredpath** [comment]
It's just occurred to me that this might not be iOS7 related, but perhaps related to the change to using presentationLayer in 586612e567f907982a11302977eb91ecc83e368b (I've just recently updated to the latest Frank HEAD). I'll do some further testing.

**Comment by lukeredpath** [comment]
Because my app is no longer compatible with iOS6, I'm unable to test if that change caused the problems. However, it does appear that crash appears to occur if the screenshot happens while there is a modal view.

**Comment by moredip** [comment]
@lukeredpath, do you know whether that new iOS7 api will capture things that are currently being animated? If so then I'd say it's a no-brainer to use it. If not then I think we'll need to investigate more. You're the first person I've heard of reporting a crash like this. I wonder whether our old technique broke in iOS7?

**Comment by ondrejhanslik** [comment]
I have actually added the `presentationLayer` only recently when I was fixigin retina screenshots. I would like to inspect the issue more because `drawViewHierarchyInRect` is not documented very well.

Would it be possible to create a simple project demonstrating the issue?

Is the problem connected to `UIWebView`? (I see a "WebCore" there). What is the actual error message?

**Comment by lukeredpath** [comment]
The error was EXC_BAD_ACCESS. The crash report doesn't seem to have much more useful information. 

The one test I identified was presenting a UIWebView in a modal view incidentally. I'm guessing from the backtrace that renderInContext was recursing through the layer hierarchy until it hit the TileHostLayer that presumably backs the web view. Good spot.

**Comment by lukeredpath** [comment]
OK, whilst I unfortunately do not have the time to put together a sample app, I can confirm that the issue appears to be related to the use of `presentationLayer` and `UIWebView`. I cannot confirm whether or not this is isolated to iOS7 or not however it seems reasonable that this bug might also exist on iOS6.

My app does not crash if I use a version with `presentationLayer` removed; it does if I leave it in. Using the new iOS7 API also fixes the problem.

As you say, the method isn't well documented so more investigation would be needed to see how it works with animation.

**Comment by mfrawley** [comment]
We are also experiencing the same issue and only since the presentationLayer change was added, we use the screenshot feature extensively in our Jenkins CI and so I guess this is just a feature not many people are using.

**Comment by ondrejhanslik** [comment]
Could you please make a commit removing only the `.presentationLayer`? I will happily merge it. Due to my work I have no time to do it myself now.

**Comment by mfrawley** [comment]
Thanks for the fast response, I'm just trying it out locally, with only that change. If that change alone fixes the crash I will make a pull request.

**Comment by ondrejhanslik** [comment]
Fixed by #253

**Comment by lukeredpath** [comment]
Should there still be some consideration to using the new iOS7 API?

**Comment by ondrejhanslik** [comment]
If you can find a use case when the new and old API differ...

**Comment by moredip** [comment]
@lukeredpath can you elaborate on why using the new API might be a better choice. Not intending to be discouraging this, just looking for more info. The downside is needing to do different things depending on what OS is running.

**Pull request closed without merging**
