### PR TITLE
Xcode4 detect and instructions

### PR DESCRIPTION
**Pull request by dlongmuir**
Hi Pete,

I don't really love this fix - I couldn't find a way to programmatically get the APP_BUNDLE_PATH for Xcode4. That being said, I think it might help some people who are struggling to get it running under Xcode4. Check it out and see if you want to pull it. (maybe just the env.rb?)

Thanks, Derek.

### CODE REVIEW

**Comment by moredip** [comment]
Can we pair on a cleaner solution to this? I want to figure out if there's some way to get a deterministic app bundle path for XCode 4. A build step or a project setting maybe.

**Comment by dlongmuir** [comment]
Sure, happy to.

D

On Sun, Mar 27, 2011 at 4:38 PM, moredip
reply@reply.github.com
wrote:

**Comment by dlongmuir** [comment]
P.S.
I tried setting the paths in the build as well and it didn't seem to
affect where the simulator-app was installed.
I also looked at the xcodebuild help without any luck.

**Comment by jollychang** [comment]
Is there simple or easy steps for Xcode4?Because I am iOS newbie,Thanks

**Comment by moredip** [comment]
I added some stuff to Frank that will do a best effort at guessing your app bundle path. I think that does as much as we can do. It can't figure out which target is the Frankified target tho.

**Pull request closed without merging**
