### PR TITLE
Support for launching retina and tall devices

### PR DESCRIPTION
**Pull request by rhgills**
Enables launching retina and tall devices, alongside proposed changes to Sim-Launcher here: https://github.com/moredip/Sim-Launcher/pull/16.

See #215.

Let me know what you think!

### CODE REVIEW

**Comment by rhgills** [comment]
Just realized this breaks the following test in launcher_test.rb:

```
it 'selects iphone mode by default' do
  launch_app(DUMMY_APP_PATH, 'X.Y')
  @version.must_equal 'iphone'
end
```

As part of my proposed changes, Sim-Launcher is responsible for defaulting to iphone. Can this test be removed, or should Frank enforce defaulting to iphone in addition to or instead of Sim-Launcher?

**Comment by rynbyjn** [comment]
Would be a nice feature for sure!
+1

**Comment by moredip** [comment]
I added a comment to https://github.com/moredip/Sim-Launcher/issues/16 asking for a couple small changes. Would like to pull this in once it's ready.

**Comment by rhgills** [comment]
Great! Replied over at https://github.com/moredip/Sim-Launcher/pull/16.

**Pull request closed without merging**
