### PR TITLE
test_on_physical_device_with_ip 

### PR DESCRIPTION
**Pull request by kkendall33**
I added the method named test_on_physical_device_with_ip which I use to specify which physical device to run the tests on.

### CODE REVIEW

**Comment by kkendall33** [comment]
Do I need to do something to get this into the project?  Or can I just wait until it gets looked at and hopefully merged?

**Comment by moredip** [comment]
This sounds like a useful feature. 

I'll take a look at this pull request when I have a moment and either pull it in or let you know what needs to change.

Cheers,

## Pete

Typed on a little bitty keyboard

**Comment by kkendall33** [comment]
Okay cool, this is my first time doing a pull request on Git, so I just wasn't sure if I was doing things right.  Thanks Pete.

**Comment by shaunmccabe** [comment]
This feature will be very helpful in my testing.

**Comment by kkendall33** [comment]
Hi Pete, would you have time to merge this pull request over the weekend?

**Comment by moredip** [comment]
Looks good. Thanks for the contribution! 

Sorry it took me so long to look over such a small change - I didn't realize it was so straightforward!

**Comment by kkendall33** [comment]
Sweet, no problem.  Thanks Pete.

**Pull request merged**
